API/urls.py
from django.conf.urls import url
from rest_framework_jwt.views import obtain_jwt_token, verify_jwt_token, refresh_jwt_token
from .views import *

urlpatterns = [
	url(r'^menu/(?P<email>[\w.%+-_]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/$', MenuUsuarioView.as_view()),
	url(r'^numseg/(?P<email>[\w.%+-_]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/$', NumeroSeguidoresView.as_view()),
	url(r'^artistas/$',TalentosView.as_view()),
	url(r'^artistas/(?P<idcategoria>[A-Za-z]+)/$', TalentosTipoView.as_view()),
	url(r'^proveedores/$',ProveedoresView.as_view()),
	url(r'^proveedores/(?P<idcategoria>[A-Za-z]+)/$',ProveedoresTipoView.as_view()),
	url(r'^castings/$',CastingsView.as_view()),
	url(r'^castings/(?P<idcategoria>[A-Za-z0-9]+)/$',CastingsTipoView.as_view()),
	url(r'^tipoarte/$', TipoArteView.as_view()),
	url(r'^tipoindustria/$', TipoIndustriaView.as_view()),
	url(r'^registro/', RegistroView.as_view()),
	url(r'^categoria/(?P<idcategoria>[A-Za-z]+)/$', UserCategoriaView.as_view()),
	url(r'^usuario/(?P<email>[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/(?P<tab>[A-Za-z]+)/$', UsuarioView.as_view()),
	url(r'^login/', obtain_jwt_token),
    url(r'^verificar/', verify_jwt_token),
    url(r'^renovar/', refresh_jwt_token),
   ]   

casting/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .views import *

urlpatterns = [
    url(r'^inicio/$', todos, name='casting_inicio'),
    url(r'^categoria/(?P<idcategoria>[A-Za-z-\w]+)/$', casting_por_categoria, name='casting_categoria'),
    url(r'^id/(?P<idcasting>[0-9]+)/$', detalle, name='casting_detalle'),
    url(r'^crear/$', login_required(crear), name='casting_crear'),
    url(r'^guardar/$', guardar, name='casting_guardar'),
    url(r'^editar/(?P<idcasting>[0-9]+)/$', editar_casting, name='casting_editar'),
    url(r'^audicion/(?P<casting>[0-9]+)/$', audicion1, name='casting_audicion1'),
    url(r'^panel/$', login_required(panel), name='panel'),
    url(r'^audicionpanel/$', login_required(audicionpanel), name='audicionpanel'),
    url(r'^industria/(?P<idcasting>[0-9]+)/$', casting_ind, name='casting_ind'),
    url(r'^audi/(?P<idaudicion>[0-9]+)/$', casting_aud, name='casting_aud'),
    url(r'^ganador/$', casting_ganador, name='casting_ganador'),
    url(r'^config/(?P<idcasting>[0-9]+)/$', login_required(config_casting), name='casting_config'),
    url(r'^borrar/(?P<idcasting>[0-9]+)/$', login_required(borrar_casting), name='casting_borrar'),
    url(r'^borrar/audicion/(?P<idaudicion>[0-9]+)/$', login_required(borrar_audicion), name='casting_borrar_audicion'),

]

ivotalents/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from frontend import views
from django.conf.urls.static import static
from django.conf import settings
from rest_framework.urlpatterns import format_suffix_patterns
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views
import notifications.urls




urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home, name='home'),
    url(r'^facebook-login/$', views.facebook_login, name='facebook'),
    url(r'^facebook-registro/$', views.facebook_registro, name='facebook-registro'),
    url(r'^registrate/$', views.registrate, name='registro'),
    url(r'^registrate/artista/$', views.registrate_artistas, name='registro_artistas'),
    url(r'^registrate/talentos/$', views.getArtes, name='registrate'),
    url(r'^registrate/generos-artisticos/$', views.getGeneroArtisticos, name='generos_artisticos'),
    url(r'^industria/$', views.industria, name='industria'),
    url(r'^ciudad/$', views.buscar_ciudad, name='ciudad'),
    url(r'^registro/industria/$', views.RegistroIndustria, name='industria'),
    url(r'^registro/proveedor/$', views.RegistroProveedor, name='proveedor'),
    url(r'^fan/$', views.fan, name='fan'),
    url(r'^registro/fan/$', views.registrofan, name='registrofan'),
    url(r'^registro/fan/interes$', views.faninteres, name='faninteres'),
    url(r'^castings/$', views.castings, name='castings'),
    url(r'^artistadashboard/$', login_required(views.artistadashboard), name='artistadashboard'),
    url(r'^busqueda-avanzada/$', login_required(views.busqueda_avanzada), name='busqueda_avanzada'),
    url(r'^industriadashboard/$', views.industriadashboard, name='industriadashboard'),
    url(r'^crearcasting/$', views.crearcasting, name='crearcasting'),
    url(r'^seleccion-registro/$', views.registrosecundario, name='seleccionregistro'),
    url(r'^seguir/$', views.seguir, name='seguir'),
    url(r'^terminos/$', views.terminos, name='terminos'),
    url(r'^planes/$', views.planes, name='planes'),
    url(r'^pagar/$', views.pagar, name='pagar'),
    url(r'^faq/$', views.faq, name='faq'),
    url(r'^faq-busqueda/$', views.busqueda_pregunta, name='busqueda_pregunta'),
    url(r'^faq-pregunta/$', views.faqpregunta, name='faqpregunta'),
    url(r'^corporativa/$', views.corporativa, name='corporativa'),
    url(r'^corporativa/contacto/$', views.contacto, name='contacto'),
    url(r'^olvido-clave/$', views.olvidoclave, name='olvidoclave'),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),

    url(r'^mensaje/get_user/', views.get_user, name='get_user'),
    url(r'^busqueda/$', views.busqueda, name='busqueda'),
    
    #url(r'^artistas/$', views.artistas, name='listado'),

    #url(r'^accounts/',include('allauth.urls')),
    url(r'^login/', views.index, name='index'),
    url(r'^logout/', views.cerrar_sesion, name='logout'),
    url(r'^perfil/', include('perfiles.urls', namespace='perfiles')),
    url(r'^all/', include('listado.urls', namespace='listado')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^casting/', include('casting.urls', namespace='casting')),
    url(r'^api/v1/', include('API.urls', namespace='api')),
    url('^inbox/notifications/', include(notifications.urls, namespace='notifications'))
    

    
]

urlpatterns = format_suffix_patterns(urlpatterns)

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

perfiles/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .views import *

urlpatterns = [
    url(r'^configuraciongeneral/foto-perfil/$', login_required(Subir_foto_perfil), name='subir_foto_perfil'),
    url(r'^configuraciongeneral/foto-cover/$', login_required(Subir_foto_cover), name='subir_foto_cover'),
    url(r'^configuraciongeneral/$', login_required(Configuracion_General), name='configuracion_general'),
    url(r'^configuraciongeneral/cita/$', login_required(Configuracion_Cita), name='configuracion_cita'),
    url(r'^configuraciongeneral/experiencia/$', login_required(ConfiguracionExperiencia), name='configuracion_experiencia'),
    url(r'^configuraciongeneral/buscar-experiencia/$', login_required(Buscar_Experiencia), name='buscar_experiencia'),
    url(r'^configuraciongeneral/actualizar-seguridad/$', login_required(Configuracion_Seguriad_Actualizar), name='configuracion_Seguridad'),
    url(r'^configuraciongeneral/actualizar-general/$', login_required(Configuracion_General_Actualizar), name='configuracion_Seguridad'),
    url(r'^configuraciongeneral/idioma/borrar/$', login_required(Borrar_Idioma), name='borrar_Idioma'),
    url(r'^configuraciongeneral/idioma/$', login_required(Agregar_Idioma), name='agregar_Idioma'),
    url(r'^configuraciongeneral/educacion/$', login_required(Configuracion_Educacion), name='configuracion_educacion'),
    url(r'^configuraciongeneral/buscar-educacion/$', login_required(Buscar_Educacion), name='buscar_educacion'),
    url(r'^configuraciongeneral/actualizar-interes/$', login_required(Configuracion_Interes), name='configuracion_interes'),
    url(r'^mensajes/detalle/$', detalle_mensajes, name='detalle_mensajes'),
    url(r'^mensajes/enviar/$', enviar_mensajes, name='enviar_mensajes'),
    url(r'^mensajes/eliminar/$', eliminar_mensajes, name='eliminar_mensajes'),
    url(r'^([0-9]+)/seguidores/$', seguidores, name='seguidores'),
    url(r'^([0-9]+)/siguiendo/$', siguiendo, name='siguiendo'),    
    url(r'^([0-9]+)/$', login_required(Perfil), name='perfil'),
    url(r'^subir_archivo/([a-z]+)/$', login_required(Subir_archivo_perfil), name='perfil'),
    url(r'^buscar-multimedia/([a-z]+)/$', login_required(Buscar_fotos), name='perfil_multimedia'),
    url(r'^borrar_archivos/$', login_required(borrar_archivos), name='borrar_archivos'),

]

casting/models.py
from django.db import models
from frontend.models import User, Industria, Etnia, Pais, Cabellos,Ojos, TipoArte, GeneroArtistico

class Categoria(models.Model):
    nombre = models.CharField(max_length=40)

    def __str__(self):
    	return self.nombre

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        app_label = 'casting'


class Casting(models.Model):
    titulo = models.CharField(max_length=255, blank=False)  # Field name made lowercase.
    fecha_inicio = models.DateTimeField(null=False)  # Field name made lowercase.
    fecha_fin = models.DateTimeField(null=False)  # Field name made lowercase.
    modifiedon = models.DateTimeField(auto_now_add=False, auto_now=True, null=True)  # Field name made lowercase.
    createdon = models.DateTimeField(auto_now_add=True ,auto_now=False, null=True)  # Field name made lowercase.
    imagen_principal = models.ImageField( upload_to='casting',blank=True)
    imagen_1 = models.ImageField(upload_to='casting', blank=True)
    imagen_2 = models.ImageField(upload_to='casting', blank=True)
    descripcion = models.TextField()
    info_destacada = models.TextField()
    info_adicional = models.TextField()
    descripcion_breve= models.CharField(max_length=255, blank=False)
    autor = models.ForeignKey(User, blank=False)
    publico = models.BooleanField(default=True)
    #filtros
    color_cabello =  models.ForeignKey(Cabellos, blank=True, null=True)
    color_ojos =  models.ForeignKey(Ojos, blank=True, null=True)
    pais = models.ForeignKey(Pais,blank=True, null=True)
    etnia =  models.ForeignKey(Etnia,blank=True, null=True)
    tatuaje = models.NullBooleanField(blank=True, null=True, default=None)


    def __str__(self):
        return self.titulo
    @property    
    def model_name(self):
        return self._meta.verbose_name

    class Meta:
        verbose_name = 'Casting'
        verbose_name_plural = 'Castings'
        app_label = 'casting'


class Filtro(models.Model):
    id_casting = models.ForeignKey(Casting, on_delete = models.CASCADE)
    id_talento = models.ForeignKey(TipoArte, on_delete = models.CASCADE)
    id_generos = models.ManyToManyField(GeneroArtistico)

    class Meta:        
        app_label = 'casting'


class Audicion(models.Model):
    id_usuario = models.ForeignKey(User)
    id_casting = models.ForeignKey(Casting)
    motivo_participar = models.TextField()
    cuentanos = models.TextField()
    archivo =  models.FileField(upload_to='audiciones', blank=False)
    ganador = models.BooleanField(default=False)
    class Meta:        
        app_label = 'casting'

    



# Create your models here.

perfiles/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from frontend.models import User
# Create your models here.

class Experiencia(models.Model):
    empresa = models.CharField(max_length=100, null=False, blank=False, verbose_name= _('Empresa'))
    cargo = models.CharField(max_length=100, null=False, blank=False, verbose_name= _('Cargo'))
    fecha_desde = models.DateField(null=False, blank=False, verbose_name=_('Desde'))
    fecha_hasta = models.DateField(null=True, blank=True, verbose_name=_('Hasta'))
    trabajo_actual = models.BooleanField(default=False, verbose_name=_('Laborando actualmente?'))
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name='experiencia')


    class Meta:
        verbose_name = 'Experiencia'
        verbose_name_plural = 'Experiencias'
        db_table = 'Experiencia_usuario'


class Educacion(models.Model):
    institucion = models.CharField(max_length=100, null=False, blank=False, verbose_name=_('Centro de Estudios'))
    fecha_inicio_estudio = models.DateField(null=False, blank=False, verbose_name=_('Fecha inicio estudios'))
    fecha_fin_estudio = models.DateField(null=True, blank=True, verbose_name=_('Fecha culmino estudios'))
    estudiando_actualmente = models.BooleanField(default=False, verbose_name=_('Estudiando actualmente'))
    titulo =models.CharField(max_length=100, null=False, blank=False, verbose_name=_('Titulo'))
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name='educacion')

    class Meta:
        verbose_name = 'Educacion'
        verbose_name_plural = 'Educacion'
        db_table = 'Educacion_usuario'


class Multimedia(models.Model):
    cluster = models.CharField(max_length=100, null=False, blank=False, verbose_name=_('Culster'))
    archivo = models.CharField(max_length=100, null=False, blank=False, verbose_name=_('Archivo'))
    nombre_archivo = models.CharField(max_length=100, null=False, blank=False, verbose_name=_('Nombre del Archivo'))
    tipo_archivo = models.CharField(max_length=1, null=False, blank=False, verbose_name=_('Tipo de archivo'))
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name='multimedia')
    estado = models.CharField(max_length=1, default='R', verbose_name=_('Estado del archivo'))

    def absolute_url(self):
        return "/media/%s%s/" % (self.cluster, self.archivo)

    class Meta:
        db_table = 'Archivos_multimedia'
        verbose_name = 'Archivo Multimedia'
        verbose_name_plural = 'Archivos Multimedia'

#falta la fecha
class Mensaje(models.Model):
    origen =  models.ForeignKey(User, on_delete=models.CASCADE, related_name='mensajes_origen')
    destino =  models.ForeignKey(User, on_delete=models.CASCADE, related_name='mensajes_destino')
    mensaje = models.TextField()
    archivo =   models.FileField(upload_to='mensajes', blank=True)
    imagen = models.ImageField(upload_to='mensajes', blank=True)

class Idioma (models.Model):
    nombre = models.CharField(max_length=20, null=False, blank=False)
    abreviatura = models.CharField(max_length=3, null=False, blank=False)
    bandera = models.ImageField(upload_to='idiomas', blank=True)

    def __str__(self):              # __unicode__ on Python 2
        return self.nombre


class UsuarioIdioma(models.Model):
    id_idioma = models.ForeignKey(Idioma, on_delete=models.CASCADE)
    id_usuario = models.ForeignKey(User, on_delete=models.CASCADE,related_name="idiomas")

casting/forms.py
from django import forms
from .models import Casting, Categoria, Audicion

class FormRegistro(forms.ModelForm):
    
    class Meta:
        model = Casting
        exclude = ['imagen_principal','descripcion_breve', 'autor','tatuaje','publico']


class FormAudicion(forms.ModelForm):
	
	class Meta:
		model = Audicion
		exclude = ['id_usuario', 'id_casting']
    		
       

perfiles/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm

from frontend.models import User
from perfiles.models import Experiencia, Educacion, Mensaje


class FormActualizarDatos(forms.ModelForm):   
    class Meta:
        model = User
        exclude = ['empresa_provedor', 'razon_social', 'direccion', 'website', 'sector', 'username','email','tipo_usuario',
                   'is_staff','is_active','last_login','is_superuser','groups','permiss', 'user_permissions', 'password',
                   'date_joined','idioma']

class FormExperiencia(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['trabajo_actual'].widget.attrs.update({'class': 'regular-radio','id' : 'radio-1-2'})

    class Meta:
        model = Experiencia
        exclude = ['usuario', 'fecha_hasta']

class FormEducacion(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['estudiando_actualmente'].widget.attrs.update({'class': 'regular-radio','id' : 'radio-1-1'})

    class Meta:
        model = Educacion
        exclude = ['usuario','fecha_fin_estudio']

class FormMensaje(forms.ModelForm):
    class Meta:
        model= Mensaje
        exclude=['origen','destino']

templates/perfiles/casting.html
{% load staticfiles %}
<!-- Blog Posts -->
		<div class="container-fluid ivo-noticiasBck">
			<div class="container">
				<div class="row ivo-noticias">
					<div class="col-sm-12 col-md-12 col-lg-12">
						<div class="row text-center">
					       	<h3 class="headermessage ivo-casting-resumen-titulo">Castings de {{datos_personales.empresa_provedor}}</h3>
					   	</div>
					    <div class="row text-center">
					    {% for casting in castings %}
					    	{% if forloop.counter0 == 0%}
					    	{% if casting.imagen_1 == ''%}
					    	<div class="image-block col-sm-8 col-md-4 col-sm-offset-2 ivo-casting-imageblock derecha" style="background: url({% static 'img/artista-t1.jpg' %}) no-repeat center top;background-size:cover;">
					    	{% else %}
					    	<div class="image-block col-sm-8 col-md-4 col-sm-offset-2 ivo-casting-imageblock derecha" style="background: url('{{casting.imagen_1.url}}') no-repeat center top;background-size:cover;">
					    	{%endif%}
					    		<h3 class="ivo-back-naranja">{{casting.categoria.nombre}}</h3>
					    		<h4 class="ivo-noticia-titulo">{{casting.titulo}}</h4>
					    		<!--h4 class="ivo-noticia-subtitulo">SubTitulo de la noticia</h4-->
					             <p class="ivo-noticia-descripcion ivo-noticia-descripcion-sub">
					            	{{casting.descripcion}}
					            </p>
					            <a href={% url 'casting:casting_detalle' idcasting=casting.id %} class="ivo-boton ivo-noticiaslink ivo-casting-noticia-link ivo-perfilINd-boton">Ver Casting</a>
					        </div>
							{% else %}
									{% if casting.imagen_1 == ''%}
					    	<div class="image-block col-sm-8 col-md-4 col-sm-offset-2 col-md-offset-0 ivo-casting-imageblock" style="background: url(http://www.prepbootstrap.com/Content/images/template/ResponsiveImageTiles/city4.jpg) no-repeat center top;background-size:cover;">
					    	{% else %}
					    	<div class="image-block col-sm-8 col-md-4 col-sm-offset-2 col-md-offset-0 ivo-casting-imageblock" style="background: url('{{casting.imagen_1.url}}') no-repeat center top;background-size:cover;">
					    	
					    	{%endif%}
								
					            <h3 class="ivo-back-naranja">{{casting.categoria.nombre}}</h3>
					    		<h4 class="ivo-noticia-titulo">{{casting.titulo}}</h4>
					    		<p class="ivo-noticia-descripcion ivo-noticia-descripcion-sub">
					            	{{casting.descripcion}}
					            </p>
					            <a href={% url 'casting:casting_detalle' idcasting=casting.id %} class="ivo-boton ivo-noticiaslink ivo-casting-noticia-link ivo-perfilINd-boton">Ver Casting</a>
					        </div>

					        {% endif %}

						{% endfor %}	




							
					    </div>
				    </div>
				</div>
			</div>
		</div>

templates/perfiles/enviar_mensaje.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}


{% block cssblock %}

		<style type="text/css">
			.ivo-pregunta { height: auto;}
			.ivo-form  select {width: 100%}
			body {background-color: white;}
			.dz-default {visibility:hidden;}
		</style>
{% endblock %}

{% block content %}

<div class="container">
			<div class="row ivo-configuracion">
				<div class="col-sm-4 col-md-3 ivo-configuracion-menu ivo-mensajes-latItems">
					<ul class="ivo-mensajes-panelSuperior">
						<li class="ivo-mensajes-botonR">
							<a href="#" class="ivo-boton-fondo ivo-boton-mensajes ivo-boton-mensajes-redactar">
								<span>Redactar</span>
							</a>
						</li>
						<li class="ivo-mensajes-select">
							<div class="dropdown">
							  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
							    <span class="icon-envelope ivo-font-azulClaro" ></span> &nbsp;<i>Mensajes Recibidos</i>
							    <span class="caret"></span>
							  </button>
							  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
							    <li><a href="#"><span class="icon-envelope ivo-font-azulClaro"></span>&nbsp; <i>Mensajes Recibidos</i></a></li>
							    <li><a href="#"><span class="icon-paper-plane ivo-font-azulClaro"></span>&nbsp; <i>Mensajes Enviados</i></a></li>
							  </ul>
							</div>					
						</li>
					</ul>
					<ul class="ivo-mensajes-lista">
						<li class="activo">
							<div class="" style="background-image: url(assets/img/avatar-ivo.jpg)"></div>
							<h5>Nombre y Apellido</h5>
							<h6>Resumen del mensaje</h6>
						</li>
						<li>
							<div class="" style="background-image: url(assets/img/avatar-ivo.jpg)"></div>
							<h5>Nombre y Apellido</h5>
							<h6>Resumen del mensaje</h6>
						</li>
						<li>
							<div class="" style="background-image: url(assets/img/avatar-ivo.jpg)"></div>
							<h5>Nombre y Apellido</h5>
							<h6>Resumen del mensaje</h6>
						</li>
						<li>
							<div class="" style="background-image: url(assets/img/avatar-ivo.jpg)"></div>
							<h5>Nombre y Apellido</h5>
							<h6>Resumen del mensaje</h6>
						</li>
						<li>
							<div class="" style="background-image: url(assets/img/avatar-ivo.jpg)"></div>
							<h5>Nombre y Apellido</h5>
							<h6>Resumen del mensaje</h6>
						</li>
						<li>
							<div class="" style="background-image: url(assets/img/avatar-ivo.jpg)"></div>
							<h5>Nombre y Apellido</h5>
							<h6>Resumen del mensaje</h6>
						</li>
					</ul>
				</div>
				<div class="col-sm-8 col-md-9 ivo-formularioConf ivo-mensajes-central">
					<form class="ivo-formularioConf-form ivo-mensaje-enviarM" method="POST" action="/perfil/mensajes/enviar/">
					{%csrf_token%}
						<!-- DEBE LLEVAR UN AJAX, O MEJOR UN SOCKET, PARA RECUPERAR LAS INSTANCIAS A LOS DATOS-->
						<input type="text" placeholder="Escribe un nombre" name="destino">
						<textarea placeholder="Escribe tu mensaje" name="mensaje"></textarea>
						<div>	
						<input type="file" id='archivo'  style="display: none;">
							
							
								<label for="archivo" class="glyphicon glyphicon-paperclip" ></label>
								
							
							<input type="file" name='imagen' style="display: none;">
								
							<label for="archivo" class="glyphicon glyphicon-picture" ></label>						
								
							
						</div>
						<button class="ivo-boton-fondoInpt ivo-borde-trs-azulClaro" style="margin-right: 3%;" type="submit">
							<span class="ivo-back-trs-azulClaro ivo-borde-transparente">Enviar</span>
						</button>
					</form>
				</div>
			</div>
		</div>

			{% endblock %}

	{% block javascript %}
	<script type="text/javascript" src="{% static 'js/dropzone.js' %}"></script>
	<!--script type="text/javascript">
            Dropzone.options.myDropzone = {
                paramName: "imagen", // el nombre de nuestro input
                autoProcessQueue : true,
                parallelUploads: 1,
                maxFiles:1,

                init: function() {
				  this.on('addedfile', function(file) {
				    if (this.files.length > 1) {
				      this.removeFile(this.files[0]);
				    }
				  });
				}

            };
        </script-->
		<script>


		    $('.carousel').carousel({
		        interval: 5000 //changes the speed
		    });

		    $('#enlace-casting').addClass('activo');


		   
				    $('#send_form').click(function(){
				    	if (validarForm( $('#form_general input') ) ) {
				        $("#form_general").submit();
		    			}
				    });
				

function registrar(){

        NProgress.start();
        $.ajax({
            url: '/casting/audicion/',
            type: 'post',
            dataType: 'json',
            data:  $('#form_general').serialize(),
            success: function (data) {
                NProgress.done();
                if(data.success == false){
                    alert(data.mensaje);
                    $.each(data.errors.fields, function(i, item) {
                        alert(i+ " "+item);
                    });
                }else{
                    alert(data.mensaje);
                    setTimeout(function(){
                      location.href  ='/casting/crear/'
                    }, 1500);

                }
            }
        });
    }

		</script>
	{% endblock %}