API/urls.py
from django.conf.urls import url
from rest_framework_jwt.views import obtain_jwt_token, verify_jwt_token, refresh_jwt_token
from .views import *

urlpatterns = [
	url(r'^menu/(?P<email>[\w.%+-_]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/$', MenuUsuarioView.as_view()),
	url(r'^numseg/(?P<email>[\w.%+-_]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/$', NumeroSeguidoresView.as_view()),
	url(r'^artistas/$',TalentosView.as_view()),
	url(r'^artistas/(?P<idcategoria>[A-Za-z]+)/$', TalentosTipoView.as_view()),
	url(r'^proveedores/$',ProveedoresView.as_view()),
	url(r'^proveedores/(?P<idcategoria>[A-Za-z]+)/$',ProveedoresTipoView.as_view()),
	url(r'^castings/$',CastingsView.as_view()),
	url(r'^castings/(?P<idcategoria>[A-Za-z0-9]+)/$',CastingsTipoView.as_view()),
	url(r'^tipoarte/$', TipoArteView.as_view()),
	url(r'^tipoindustria/$', TipoIndustriaView.as_view()),
	url(r'^registro/', RegistroView.as_view()),
	url(r'^categoria/(?P<idcategoria>[A-Za-z]+)/$', UserCategoriaView.as_view()),
	url(r'^usuario/(?P<email>[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/(?P<tab>[A-Za-z]+)/$', UsuarioView.as_view()),
	url(r'^login/', obtain_jwt_token),
    url(r'^verificar/', verify_jwt_token),
    url(r'^renovar/', refresh_jwt_token),
   ]   

ivotalents/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from frontend import views
from django.conf.urls.static import static
from django.conf import settings
from rest_framework.urlpatterns import format_suffix_patterns
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views
import notifications.urls




urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home, name='home'),
    url(r'^facebook-login/$', views.facebook_login, name='facebook'),
    url(r'^facebook-registro/$', views.facebook_registro, name='facebook-registro'),
    url(r'^registrate/$', views.registrate, name='registro'),
    url(r'^registrate/artista/$', views.registrate_artistas, name='registro_artistas'),
    url(r'^registrate/talentos/$', views.getArtes, name='registrate'),
    url(r'^registrate/generos-artisticos/$', views.getGeneroArtisticos, name='generos_artisticos'),
    url(r'^industria/$', views.industria, name='industria'),
    url(r'^ciudad/$', views.buscar_ciudad, name='ciudad'),
    url(r'^registro/industria/$', views.RegistroIndustria, name='industria'),
    url(r'^registro/proveedor/$', views.RegistroProveedor, name='proveedor'),
    url(r'^fan/$', views.fan, name='fan'),
    url(r'^registro/fan/$', views.registrofan, name='registrofan'),
    url(r'^registro/fan/interes$', views.faninteres, name='faninteres'),
    url(r'^castings/$', views.castings, name='castings'),
    url(r'^artistadashboard/$', login_required(views.artistadashboard), name='artistadashboard'),
    url(r'^busqueda-avanzada/$', login_required(views.busqueda_avanzada), name='busqueda_avanzada'),
    url(r'^industriadashboard/$', views.industriadashboard, name='industriadashboard'),
    url(r'^crearcasting/$', views.crearcasting, name='crearcasting'),
    url(r'^seleccion-registro/$', views.registrosecundario, name='seleccionregistro'),
    url(r'^seguir/$', views.seguir, name='seguir'),
    url(r'^terminos/$', views.terminos, name='terminos'),
    url(r'^planes/$', views.planes, name='planes'),
    url(r'^pagar/$', views.pagar, name='pagar'),
    url(r'^faq/$', views.faq, name='faq'),
    url(r'^faq-busqueda/$', views.busqueda_pregunta, name='busqueda_pregunta'),
    url(r'^faq-pregunta/$', views.faqpregunta, name='faqpregunta'),
    url(r'^corporativa/$', views.corporativa, name='corporativa'),
    url(r'^corporativa/contacto/$', views.contacto, name='contacto'),
    url(r'^olvido-clave/$', views.olvidoclave, name='olvidoclave'),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),

    url(r'^mensaje/get_user/', views.get_user, name='get_user'),
    url(r'^busqueda/$', views.busqueda, name='busqueda'),
    
    #url(r'^artistas/$', views.artistas, name='listado'),

    #url(r'^accounts/',include('allauth.urls')),
    url(r'^login/', views.index, name='index'),
    url(r'^logout/', views.cerrar_sesion, name='logout'),
    url(r'^perfil/', include('perfiles.urls', namespace='perfiles')),
    url(r'^all/', include('listado.urls', namespace='listado')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^casting/', include('casting.urls', namespace='casting')),
    url(r'^api/v1/', include('API.urls', namespace='api')),
    url('^inbox/notifications/', include(notifications.urls, namespace='notifications'))
    

    
]

urlpatterns = format_suffix_patterns(urlpatterns)

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

listado/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .views import *

urlpatterns = [
    url(r'^artistas/$', artistas, name='artistas'),
    url(r'^artistas/(?P<idcategoria>[0-9]+)/$', artista_por_categoria, name='artista_categoria'),
    url(r'^industrias/$', industrias, name='industrias'),
    url(r'^industrias/(?P<idcategoria>[0-9]+)/$', industria_por_categoria, name='industria_categoria'),
    url(r'^proveedores/$', proveedores, name='proveedores'),
    url(r'^proveedores/(?P<idcategoria>[0-9]+)/$', proveedor_por_categoria, name='proveedor_categoria'),
   
]

listado/views.py
from django.shortcuts import render_to_response, render
from frontend.models import  User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from blog.models import Post
from frontend.models import UsuarioArteGenero, TipoArte, GeneroArtistico, UsuarioArte, SectorIndustria, Industria

# Create your views here.





def artistas(request):

	posts = Post.objects.all().order_by("-fecha_creacion")[:5]
	all_users = UsuarioArteGenero.objects.all()
	paginator = Paginator(all_users, 12) # Show 25 contacts per page
	tipoartes= TipoArte.objects.all()
	page = request.GET.get('page',1)
	try:
		result = paginator.page(page)
	except PageNotAnInteger:
        # If page is not an integer, deliver first page.
		result = paginator.page(1)
	except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
		result = paginator.page(paginator.num_pages)
	#import pdb;   pdb.set_trace()
	return render(request, "listado/artistas.html", {"artistas":result, "posts":posts, 'tipoartes':tipoartes } )



def artista_por_categoria(request, idcategoria):
	posts = Post.objects.all().order_by("-fecha_creacion")[:5]
	#categoria = TipoArte.objects.get(name=idcategoria)
	generos = GeneroArtistico.objects.filter(id_tipo_arte=idcategoria).values('id')
	all_users = UsuarioArteGenero.objects.filter(id_genero__in=generos)
	tipoartes= TipoArte.objects.all()
	paginator = Paginator(all_users, 12) # Show 25 contacts per page	
	page = request.GET.get('page',1)
	try:
		result = paginator.page(page)
	except PageNotAnInteger:
        # If page is not an integer, deliver first page.
		result = paginator.page(1)
	except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
		result = paginator.page(paginator.num_pages)
	#import pdb;   pdb.set_trace()
	return render(request,"listado/artistas.html", {"artistas":result, "posts":posts,'tipoartes':tipoartes } )


def industrias(request):

	posts = Post.objects.all().order_by("-fecha_creacion")[:5]
	all_users = SectorIndustria.objects.filter(id_usuario__in=User.objects.filter(tipo_usuario='I').values_list('id',flat=True))
	paginator = Paginator(all_users, 12) # Show 25 contacts per page
	tipoindustrias= Industria.objects.filter(tipo='I')
	page = request.GET.get('page',1)
	try:
		result = paginator.page(page)
	except PageNotAnInteger:
        # If page is not an integer, deliver first page.
		result = paginator.page(1)
	except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
		result = paginator.page(paginator.num_pages)
	#import pdb;   pdb.set_trace()
	return render(request, "listado/industrias.html", {"industrias":result, "posts":posts, 'tipoindustrias':tipoindustrias } )


# FALLA CON CUALQUIER REGISTRO NUEVO?

def industria_por_categoria(request, idcategoria):
	posts = Post.objects.all().order_by("-fecha_creacion")[:5]
	#categoria = Industria.objects.get(nombre=idcategoria)
	all_users = SectorIndustria.objects.filter(id_sector=idcategoria)
	tipoindustrias= Industria.objects.all()
	paginator = Paginator(all_users, 12) # Show 25 contacts per page	
	page = request.GET.get('page',1)
	try:
		result = paginator.page(page)
	except PageNotAnInteger:
        # If page is not an integer, deliver first page.
		result = paginator.page(1)
	except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
		result = paginator.page(paginator.num_pages)
	#import pdb;   pdb.set_trace()
	return render(request,"listado/industrias.html", {"industrias":result, "posts":posts,'tipoindustrias':tipoindustrias } )


def proveedores(request):

	posts = Post.objects.all().order_by("-fecha_creacion")[:5]
	all_users = SectorIndustria.objects.filter(id_usuario__in=User.objects.filter(tipo_usuario='P').values_list('id',flat=True))
	paginator = Paginator(all_users, 12) # Show 25 contacts per page
	tipoindustrias= Industria.objects.filter(tipo='P')
	page = request.GET.get('page',1)
	try:
		result = paginator.page(page)
	except PageNotAnInteger:
        # If page is not an integer, deliver first page.
		result = paginator.page(1)
	except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
		result = paginator.page(paginator.num_pages)
	#import pdb;   pdb.set_trace()
	return render(request, "listado/proveedores.html", {"industrias":result, "posts":posts, 'tipoindustrias':tipoindustrias } )


# FALLA CON CUALQUIER REGISTRO NUEVO?

def proveedor_por_categoria(request, idcategoria):
	posts = Post.objects.all().order_by("-fecha_creacion")[:5]
	#categoria = Industria.objects.get(nombre=idcategoria)
	all_users = SectorIndustria.objects.filter(id_sector=idcategoria)
	tipoindustrias= Industria.objects.all()
	paginator = Paginator(all_users, 12) # Show 25 contacts per page	
	page = request.GET.get('page',1)
	try:
		result = paginator.page(page)
	except PageNotAnInteger:
        # If page is not an integer, deliver first page.
		result = paginator.page(1)
	except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
		result = paginator.page(paginator.num_pages)
	#import pdb;   pdb.set_trace()
	return render(request,"listado/proveedores.html", {"industrias":result, "posts":posts,'tipoindustrias':tipoindustrias } )

templates/listado/artistas.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}


{% block cssblock %}

		<style type="text/css">
			.ivo-pregunta { height: auto;}
			.ivo-form  select {width: 100%}
			.ivo-imgListado {
								width: 110px;
								height: 110px;
							    background-size: cover;
							    background-position: center;
							    cursor:pointer;
							    background-repeat: no repeat;
							}
			.ivo-artistas {
				background-image: url("{% static 'img/artistas-header.jpg' %}");
			}

			.ivo-layer-gry {
				height: 550px;
			}
		</style>
{% endblock %}

{% block content %}




<div class="container-fluid ivo-artistas">
			<div class="ivo-layer-gry ivo-layer-gry-artistas"></div>
			<div class="container">
			<div class="row">
				<div class="col-xs-8 col-sm-6 col-md-6 col-lg-6">
					<h1>
						<span>Juan Esteban</span>
						</br>
						Cantante
					</h1>
				</div>
			</div>
			</div>
		</div>
		<!-- Artistas -->
		<div class="container-fluid ivo-artistas-bck-cont">
			<div class="container">
				<div class="row ivo-artistas-panel">
					<div class="col-xs-10 col-sm-10 col-md-12 col-lg-12 col-xs-offset-1 col-sm-offset-1 col-md-offset-0 col-lg-offset-0">
						<div class="row text-center ivo-artistas-panel-texto">
							<h1 class="headermessage">Artistas</h1>
					       	<h3 class="headermessage">Conoce a los talentos mas recientes</h3>
					       	<ul class="list-inline ivo-artistas-panel-filtros">

					       	<!-- SE PUEDE AUTOMATIZAR PARA QUE SE GENEREN LOS LINKS SOLOS-->

					       	{% for tipoarte in tipoartes %}

							  <li> <a style="text-decoration: none; color: white;" href={% url 'listado:artista_categoria' idcategoria=tipoarte.id %} >{{tipoarte.name}}</a>  </li>
							
							 
							 {% endfor %}
							</ul>
					   	</div>

					   {% if artistas.object_list|length == 0 %}
								<h4> No hay resultados para esta busqueda</h4>
							{% endif %}

					   	{% for artista in artistas %}
					   		<!-- ESTO PUEDE NO ESTARSE EJECUTANDO NUNCA-->
							{% if artista.counter0 == 0 or artista.counter0 == 6 %}
					   		 <div class="row">
							{% endif %}
							
					        <div class="col-xs-4 col-sm-4 col-md-2 ivo-artistas-panel-item" >

					       
					        	{% if artista.id_usuario.avatar %}
					        	
					        	<!--img src="{{ artista.id_usuario.avatar.url }}/" class="img-responsive"-->
					        	<a href="/perfil/{{artista.id_usuario.id}}/">
								<div class="ivo-imgListado" style="background-image: url(/media/{{artista.id_usuario.avatar}});"></div>
					        		</a>

					        	{%  else %}	

						<!-- REVISAR ESTO ... NECESITO IMAGEN POR DEFECTO PARA USUARIO -->
					        	
					        	<!--img src="http://www.prepbootstrap.com/Content/images/template/ResponsiveImageTiles/city4.jpg" class="img-responsive"-->
								<a href="/perfil/{{artista.id_usuario.id}}/">
					        	<div class="ivo-imgListado" style="background-image: url(http://www.prepbootstrap.com/Content/images/template/ResponsiveImageTiles/city4.jpg);"></div>
					        		</a>

					        	{% endif %}			            
					            <h3>{{artista.id_genero.id_tipo_arte.name}}</h3> 
					    		<h4 class="nombre">{{ artista.id_usuario.get_full_name }}</h4>
					    		<h4>{{artista.id_genero.name}}</h4>
					        
					        	
					        </div>
       						 
       					
   						 {% endfor %}
       				
					   
					    </div>    
					   
					   <div class="row">
					   		<div class="col-md-4 col-md-offset-4 text-center">
					   			{% if artistas.has_other_pages %}
					   			<ul class="ivo-panel-indice">
					   				{% for i in artistas.paginator.page_range %}
							      	{% if artistas.number == i %}
									<li class="activo"><span class="icon_circle-slelected"></span></li>
									{% else %}
									<li>
										<a href="?page={{ i }}">
											<span class="icon_circle-empty"></span>
										</a>
										</li>
									{% endif %}
							    {% endfor %}
								</ul>
								{% endif %}
					   		</div>
					   </div>
				    </div>
				</div>
			</div>
		</div>
		<!-- App -->
		<div class="container-fluid ivo-artistas-appBck">
			<div class="container">
				<div class="row">
					<div class="col-md-12 col-lg-12 ivo-artistas-app">
						<div class="row">
							<div class="col-sm-8 col-sm-offset-2 col-md-5 col-md-offset-0 col-lg-5 col-lg-offset-0">
								<img src="{% static 'img/ivo-lg3.png' %}" class="img-responsive ivo-app-logo general">
								<h2>Descarga nuestra App Movil</h2>
								<a href="#" class="ivo-app-goplay general">
									<img src="{% static 'img/google-play.png' %} ">
								</a>
								<a href="#" class="ivo-app-appsto general">
									<img src="{% static 'img/appstore.png' %}">
								</a>
								<br class="clear">
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>


		<!-- Blog Posts -->
		<div class="container-fluid ivo-artistas-bck-cont">
			<div class="container">
				<div class="row ivo-noticias">
					<div class="col-md-12 col-lg-12">
						<div class="row text-left">
					       	<h3 class="headermessage">&Uacute;ltimas Entradas</h3>
					   	</div>
					    <div class="row">
							{% for post in posts %}
								{% if forloop.counter0 == 0 %}
									<div class="image-block col-xs-6 col-sm-4" style="background: url('{{post.imagen.url}}'); no-repeat center top;background-size:cover;">

								{% if post.categoria.nombre == 'Novedades' %}

								<h3 class="ivo-back-rosa">{{post.categoria}}</h3>					    		

								{% elif post.categoria.nombre == 'Fanatico' %}

								<h3 class="ivo-back-azulClaro">{{post.categoria}}</h3>

								{% elif post.categoria.nombre == 'Industria' %}

								<h3 class="ivo-back-azul">{{post.categoria}}</h3>

								{% elif post.categoria.nombre == 'Casting' %}

								<h3 class="ivo-back-verde-c">{{post.categoria}}</h3>

								{% else %}

								<h3 class="ivo-back-naranja">{{post.categoria}}</h3>

								{% endif %}
								

					    		<h4 class="ivo-noticia-titulo">{{post.titulo}}</h4>
					            <p class="ivo-noticia-descripcion">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>
					            <a href={% url 'blog:detalle' idpost=post.id %} class="ivo-boton ivo-noticiaslink ivo-casting-noticia-link">Leer Mas</a>
					            <div class="ivo-layer ivo-noticia-layer ivo-layer-light"></div>

					    		

					        </div>

								{% elif forloop.counter0 == 1 %}
								<div class="image-block col-xs-6 col-sm-4" style="background: url('{{post.imagen.url}}'); no-repeat center top;background-size:cover;">

					            {% if post.categoria.nombre == 'Novedades' %}

								<h3 class="ivo-back-rosa">{{post.categoria}}</h3>					    		

								{% elif post.categoria.nombre == 'Fanatico' %}

								<h3 class="ivo-back-azulClaro">{{post.categoria}}</h3>

								{% elif post.categoria.nombre == 'Industria' %}

								<h3 class="ivo-back-azul">{{post.categoria}}</h3>

								{% elif post.categoria.nombre == 'Casting' %}

								<h3 class="ivo-back-verde-c">{{post.categoria}}</h3>

								{% else %}

								<h3 class="ivo-back-naranja">{{post.categoria}}</h3>

								{% endif %}

					    		<h4 class="ivo-noticia-titulo">{{post.titulo}}</h4>
					            <p class="ivo-noticia-descripcion">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante.</p>
					            <a href={% url 'blog:detalle' idpost=post.id %} class="ivo-boton ivo-noticiaslink ivo-casting-noticia-link">Leer Mas</a>
					            <div class="ivo-layer ivo-noticia-layer ivo-layer-light"></div>
					        </div>

								{% elif forloop.counter0 == 2 %}

								 <div class="image-block col-xs-6 col-sm-4" style="background: url('{{post.imagen.url}}'); no-repeat center top;background-size:cover;">
								           
								{% if post.categoria.nombre == 'Novedades' %}

								<h3 class="ivo-back-rosa">{{post.categoria}}</h3>					    		

								{% elif post.categoria.nombre == 'Fanatico' %}

								<h3 class="ivo-back-azulClaro">{{post.categoria}}</h3>

								{% elif post.categoria.nombre == 'Industria' %}

								<h3 class="ivo-back-azul">{{post.categoria}}</h3>

								{% elif post.categoria.nombre == 'Casting' %}

								<h3 class="ivo-back-verde-c">{{post.categoria}}</h3>

								{% else %}

								<h3 class="ivo-back-naranja">{{post.categoria}}</h3>

								{% endif %}

					    		<h4 class="ivo-noticia-titulo">{{post.titulo}}</h4>
					            <p class="ivo-noticia-descripcion">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>
					            <a href={% url 'blog:detalle' idpost=post.id %} class="ivo-boton ivo-noticiaslink ivo-casting-noticia-link">Leer Mas</a>
					            <div class="ivo-layer ivo-noticia-layer ivo-layer-light"></div>
					        </div>

								{% elif forloop.counter0 == 3 %}

								<div class="image-block col-xs-6 col-sm-8" style="background: url('{{post.imagen.url}}'); no-repeat center top;background-size:cover;">

								{% if post.categoria.nombre == 'Novedades' %}

								<h3 class="ivo-back-rosa">{{post.categoria}}</h3>					    		

								{% elif post.categoria.nombre == 'Fanatico' %}

								<h3 class="ivo-back-azulClaro">{{post.categoria}}</h3>

								{% elif post.categoria.nombre == 'Industria' %}

								<h3 class="ivo-back-azul">{{post.categoria}}</h3>

								{% elif post.categoria.nombre == 'Casting' %}

								<h3 class="ivo-back-verde-c">{{post.categoria}}</h3>

								{% else %}

								<h3 class="ivo-back-naranja">{{post.categoria}}</h3>

								{% endif %}
					            
					    		<h4 class="ivo-noticia-titulo">{{post.titulo}}</h4>
					            <p class="ivo-noticia-descripcion">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>
					            <a href={% url 'blog:detalle' idpost=post.id %} class="ivo-boton ivo-noticiaslink ivo-casting-noticia-link">Leer Mas</a>
					            <div class="ivo-layer ivo-noticia-layer ivo-layer-light"></div>
					        </div>

								{% elif forloop.counter0 == 4 %}			    	
					        
					       
					        
					        <div class="image-block col-xs-6 col-sm-4" style="background: url('{{post.imagen.url}}'); no-repeat center top;background-size:cover;">

					            {% if post.categoria.nombre == 'Novedades' %}

								<h3 class="ivo-back-rosa">{{post.categoria}}</h3>					    		

								{% elif post.categoria.nombre == 'Fanatico' %}

								<h3 class="ivo-back-azulClaro">{{post.categoria}}</h3>

								{% elif post.categoria.nombre == 'Industria' %}

								<h3 class="ivo-back-azul">{{post.categoria}}</h3>

								{% elif post.categoria.nombre == 'Casting' %}

								<h3 class="ivo-back-verde-c">{{post.categoria}}</h3>

								{% else %}

								<h3 class="ivo-back-naranja">{{post.categoria}}</h3>

								{% endif %}

					    		<h4 class="ivo-noticia-titulo">{{post.titulo}}</h4>
					            <p class="ivo-noticia-descripcion">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>
					            <a href={% url 'blog:detalle' idpost=post.id %} class="ivo-boton ivo-noticiaslink ivo-casting-noticia-link">Leer Mas</a>
					            <div class="ivo-layer ivo-noticia-layer ivo-layer-light"></div>      
					        </div>

					        {% endif %}
					    	{% endfor %}
					    </div>
				    </div>
				</div>
			</div>
		</div>
		{% endblock %}

	{% block javascript %}
		<script>
		    $('.carousel').carousel({
		        interval: 5000 //changes the speed
		    })
	    

		    $('#enlace-talentos').addClass('activo');
	
		</script>
	{% endblock %}