API/urls.py
from django.conf.urls import url
from rest_framework_jwt.views import obtain_jwt_token, verify_jwt_token, refresh_jwt_token
from .views import *

urlpatterns = [
	url(r'^menu/(?P<email>[\w.%+-_]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/$', MenuUsuarioView.as_view()),
	url(r'^numseg/(?P<email>[\w.%+-_]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/$', NumeroSeguidoresView.as_view()),
	url(r'^artistas/$',TalentosView.as_view()),
	url(r'^artistas/(?P<idcategoria>[A-Za-z]+)/$', TalentosTipoView.as_view()),
	url(r'^proveedores/$',ProveedoresView.as_view()),
	url(r'^proveedores/(?P<idcategoria>[A-Za-z]+)/$',ProveedoresTipoView.as_view()),
	url(r'^castings/$',CastingsView.as_view()),
	url(r'^castings/(?P<idcategoria>[A-Za-z0-9]+)/$',CastingsTipoView.as_view()),
	url(r'^tipoarte/$', TipoArteView.as_view()),
	url(r'^tipoindustria/$', TipoIndustriaView.as_view()),
	url(r'^registro/', RegistroView.as_view()),
	url(r'^categoria/(?P<idcategoria>[A-Za-z]+)/$', UserCategoriaView.as_view()),
	url(r'^usuario/(?P<email>[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/(?P<tab>[A-Za-z]+)/$', UsuarioView.as_view()),
	url(r'^login/', obtain_jwt_token),
    url(r'^verificar/', verify_jwt_token),
    url(r'^renovar/', refresh_jwt_token),
   ]   

blog/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^all/$', todos, name='todos'),    
    url(r'^post/(?P<idpost>[0-9]+)/$', detalle, name='detalle'),
    url(r'^busqueda/$', busqueda, name='busqueda'),
    url(r'^(?P<idcategoria>[A-Za-z]+)/$', posts_por_categoria, name='categoria'),

   
]

ivotalents/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from frontend import views
from django.conf.urls.static import static
from django.conf import settings
from rest_framework.urlpatterns import format_suffix_patterns
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views
import notifications.urls




urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home, name='home'),
    url(r'^facebook-login/$', views.facebook_login, name='facebook'),
    url(r'^facebook-registro/$', views.facebook_registro, name='facebook-registro'),
    url(r'^registrate/$', views.registrate, name='registro'),
    url(r'^registrate/artista/$', views.registrate_artistas, name='registro_artistas'),
    url(r'^registrate/talentos/$', views.getArtes, name='registrate'),
    url(r'^registrate/generos-artisticos/$', views.getGeneroArtisticos, name='generos_artisticos'),
    url(r'^industria/$', views.industria, name='industria'),
    url(r'^ciudad/$', views.buscar_ciudad, name='ciudad'),
    url(r'^registro/industria/$', views.RegistroIndustria, name='industria'),
    url(r'^registro/proveedor/$', views.RegistroProveedor, name='proveedor'),
    url(r'^fan/$', views.fan, name='fan'),
    url(r'^registro/fan/$', views.registrofan, name='registrofan'),
    url(r'^registro/fan/interes$', views.faninteres, name='faninteres'),
    url(r'^castings/$', views.castings, name='castings'),
    url(r'^artistadashboard/$', login_required(views.artistadashboard), name='artistadashboard'),
    url(r'^busqueda-avanzada/$', login_required(views.busqueda_avanzada), name='busqueda_avanzada'),
    url(r'^industriadashboard/$', views.industriadashboard, name='industriadashboard'),
    url(r'^crearcasting/$', views.crearcasting, name='crearcasting'),
    url(r'^seleccion-registro/$', views.registrosecundario, name='seleccionregistro'),
    url(r'^seguir/$', views.seguir, name='seguir'),
    url(r'^terminos/$', views.terminos, name='terminos'),
    url(r'^planes/$', views.planes, name='planes'),
    url(r'^pagar/$', views.pagar, name='pagar'),
    url(r'^faq/$', views.faq, name='faq'),
    url(r'^faq-busqueda/$', views.busqueda_pregunta, name='busqueda_pregunta'),
    url(r'^faq-pregunta/$', views.faqpregunta, name='faqpregunta'),
    url(r'^corporativa/$', views.corporativa, name='corporativa'),
    url(r'^corporativa/contacto/$', views.contacto, name='contacto'),
    url(r'^olvido-clave/$', views.olvidoclave, name='olvidoclave'),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),

    url(r'^mensaje/get_user/', views.get_user, name='get_user'),
    url(r'^busqueda/$', views.busqueda, name='busqueda'),
    
    #url(r'^artistas/$', views.artistas, name='listado'),

    #url(r'^accounts/',include('allauth.urls')),
    url(r'^login/', views.index, name='index'),
    url(r'^logout/', views.cerrar_sesion, name='logout'),
    url(r'^perfil/', include('perfiles.urls', namespace='perfiles')),
    url(r'^all/', include('listado.urls', namespace='listado')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^casting/', include('casting.urls', namespace='casting')),
    url(r'^api/v1/', include('API.urls', namespace='api')),
    url('^inbox/notifications/', include(notifications.urls, namespace='notifications'))
    

    
]

urlpatterns = format_suffix_patterns(urlpatterns)

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.

class Categoria(models.Model):
    nombre = models.CharField(max_length=20)

    def __str__(self):
    	return self.nombre


class Post(models.Model):	
	imagen = models.ImageField( blank=True)
	titulo = models.CharField(max_length=200)
	contenido = models.TextField()
	categoria = models.ForeignKey(Categoria)
	fecha_creacion = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.titulo

blog/forms.py
from django import forms

class FormBusqueda(forms.Form):
   consulta = forms.CharField(max_length = 50)

blog/views.py
from django.shortcuts import render_to_response, render, redirect
from django.views.generic import TemplateView
from .models import Categoria, Post
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from  blog.forms import FormBusqueda
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from functools import reduce
from django.db.models import Q
# Create your views here.






def todos(request):
	#import pdb;   pdb.set_trace()
	all_posts = Post.objects.all().order_by("-fecha_creacion")
	paginator = Paginator(all_posts, 5) # Show 25 contacts per page

	page = request.GET.get('page',1)
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
        # If page is not an integer, deliver first page.
		posts = paginator.page(1)
	except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
		posts = paginator.page(paginator.num_pages)
		#import pdb;   pdb.set_trace()
	return render(request, "blog/blog.html", {"posts": posts })


#def todos(request):
#	posts = Post.objects.order_by("-fecha_creacion")
	


def posts_por_categoria(request, idcategoria):
	categoria = Categoria.objects.get(nombre=idcategoria)
	all_posts = categoria.post_set.order_by("-fecha_creacion")
	paginator = Paginator(all_posts, 5) # Show 25 contacts per page	
	page = request.GET.get('page',1)
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
        # If page is not an integer, deliver first page.
		posts = paginator.page(1)
	except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
		posts = paginator.page(paginator.num_pages)
		#import pdb;   pdb.set_trace()
		
	return render(request, "blog/blog.html", {"posts": posts })



def detalle(request,idpost):

	post = Post.objects.get(id=idpost)
	#import pdb;   pdb.set_trace()
	return render(request,"blog/post.html", {"post": post, },)


def busqueda(request):

	
	terms = request.GET['q']
	term_list = terms.split(' ')

	results = Post.objects.all()

	qq = Q(titulo__icontains=term_list[0]) | Q(contenido__icontains=term_list[0])
	for term in term_list[1:]:
		qq.add((Q(contenido__icontains=term) | Q(titulo__icontains=term)), qq.connector)

	results = results.filter(qq)
	
	#import pdb;pdb.set_trace()
	paginator = Paginator(results, 6)
	page = request.GET.get('page',1)
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:	       
		posts = paginator.page(1)
	except EmptyPage:	       
		posts = paginator.page(paginator.num_pages)			
	return render(request,"blog/resultados.html", {"posts": posts})
	

templates/blog/post.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}


{% block cssblock %}

		<style type="text/css">
			.ivo-pregunta { height: auto;}
			.ivo-form  select {width: 100%}
			body {background-color: white;}
		</style>
		
{% endblock %}


 {% block content%}
<!-- Blog Entrada Barra Superior-->
		<div class="container">
			<div class="row hidden-md hidden-lg ivo-entrada-smTop">
				<div class="col-sm-12 ivo-entrada-busqueda">
					<h4>Buscar Articulo</h4>
					<!--form id="busqueda" action="/blog/busqueda/consulta=df" method="GET"  -->
					<form id="busqueda" action="{% url 'blog:busqueda' %}" method="GET" >							
						<input type="text" name="q" placeholder="Consulta">

						<button type="submit">
							<span class="glyphicon glyphicon-search"></span>
						</button>
						
					</form>
				</div>

				<div class="col-sm-12 ivo-entrada-categoriaTop">
					{% if post.categoria.nombre == 'Novedades' %}					
						<span class="ivo-entrada-contenido-categoria ivo-back-rosa">{{post.categoria.nombre}}</span>
					{% elif post.categoria.nombre == 'Fanatico' %}						
						<span class="ivo-entrada-contenido-categoria ivo-back-azulClaro">{{post.categoria.nombre}}</span>
					{% elif post.categoria.nombre == 'Industria' %}					
						<span class="ivo-entrada-contenido-categoria ivo-back-azul">{{post.categoria.nombre}}</span>
					{% elif post.categoria.nombre == 'Casting' %}					
						<span class="ivo-entrada-contenido-categoria ivo-back-verde-c">{{post.categoria.nombre}}</span>
					{% else %}			
					<span class="ivo-entrada-contenido-categoria ivo-back-naranja">{{post.categoria.nombre}}</span>
					{% endif %}


					
				</div>
			</div>
			<div class="row ivo-entrada row ivo-entrada-topEnt">
				<div class="col-md-9 col-lg-9 ivo-entrada-titulo">
					{% if post.categoria.nombre == 'Novedades' %}
						<h1 class="ivo-borde-rosa">{{post.titulo}}</h1>
					{% elif post.categoria.nombre == 'Fanatico' %}
						<h1 class="ivo-borde-azulClaro">{{post.titulo}}</h1>
					{% elif post.categoria.nombre == 'Industria' %}
						<h1 class="ivo-borde-azul">{{post.titulo}}</h1>
					{% elif post.categoria.nombre == 'Casting' %}
						<h1 class="ivo-borde-verde-c">{{post.titulo}}</h1>
					{% else %}
					<h1 class="ivo-borde-naranja">{{post.titulo}}</h1>
					{% endif %}
				</div>
				<div class="col-md-3 col-lg-3 ivo-entrada-busqueda hidden-xs hidden-sm">
					<h4>Buscar Articulo</h4>
					<form id="busqueda" action="{% url 'blog:busqueda' %}" method="GET" >							
						<input type="text" name="q" placeholder="Consulta">

						<button type="submit">
							<span class="glyphicon glyphicon-search"></span>
						</button>
							
						
					</form>
					
				</div>
			</div>
			<div class="row">
				<div class="col-md-2 col-lg-2 ivo-entrada-social">
					<h4>Compartir</h4>
					<a href="http://www.facebook.com/share.php?u=http://example.com/blog/1&title={{post.titulo}}">
						<span class="social_facebook_circle"></span>
					</a>					


					<a href="http://twitter.com/intent/tweet?status={{post.titulo}}+http://example.com/blog/1">
						<span class="social_twitter_circle"></span>
					</a>
						
				</div>
				<div class="col-md-7 col-lg-7 ivo-entrada-contenido">
					{% if post.categoria.nombre == 'Novedades' %}
						<span class="ivo-entrada-contenido-categoria ivo-back-rosa hidden-xs hidden-sm">{{post.categoria.nombre}}</span>
					{% elif post.categoria.nombre == 'Fanatico' %}
						<span class="ivo-entrada-contenido-categoria ivo-back-azulClaro hidden-xs hidden-sm">{{post.categoria.nombre}}</span>
					{% elif post.categoria.nombre == 'Industria' %}
						<span class="ivo-entrada-contenido-categoria ivo-back-azul hidden-xs hidden-sm">{{post.categoria.nombre}}</span>
					{% elif post.categoria.nombre == 'Casting' %}
						<span class="ivo-entrada-contenido-categoria ivo-back-verde-c hidden-xs hidden-sm">{{post.categoria.nombre}}</span>
					{% else %}
						<span class="ivo-entrada-contenido-categoria ivo-back-naranja hidden-xs hidden-sm">{{post.categoria.nombre}}</span>
					{% endif %}

					
					<div class="ivo-entrada-contenido-fecha">{{post.fecha_creacion}}</div>
					<img src="{{post.imagen.url}}" class="img-responsive ivo-entrada-imagen">
					{{post.contenido | safe}}
				</div>
				<div class="col-md-3 col-lg-3 ivo-entrada-categorias">
					<h4>Categor&iacute;as</h4>
					<ul>
						<li style="background-color:#D8006C;"><a href={% url 'blog:categoria' idcategoria='Novedades' %}>Novedades</a></li>
						<li style="background-color:#FC4513;"><a href={% url 'blog:categoria' idcategoria='Talento' %}>Talento</a></li>
						<li style="background-color:#00C4B4;"><a href={% url 'blog:categoria' idcategoria='Fanatico' %}>Fans</a></li>
						<li style="background-color:#61A60E;"><a href={% url 'blog:categoria' idcategoria='Casting' %}>Casting</a></li>
						<li style="background-color:#0032A0;"><a href={% url 'blog:categoria' idcategoria='Industria' %}>Industria</a></li>
					</ul>
					<div class="ivo-entradas-relacion">
						<h4><font>Entradas</font></br> Recomendadas</h4>
						<ul>
							<li>
								<img src="{% static 'img/proveedores.jpg' %}" class="img-responsive">
								<div class="ivo-borde-naranja">Talento</div>
								<p>
									Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
								</p>
							</li>
							<li>
								<img src={"% static 'img/proveedores.jpg' %}" class="img-responsive">
								<div class="ivo-borde-verde">Casting</div>
								<p>
									Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
								</p>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
		<!-- App -->
		<div class="container-fluid ivo-artistas-appBck">
			<div class="container">
				<div class="row">
					<div class="col-md-12 col-lg-12 ivo-artistas-app">
						<div class="row">
							<div class="col-sm-8 col-sm-offset-2 col-md-5 col-md-offset-0 col-lg-5 col-lg-offset-0">
								<img src="{% static 'img/ivo-lg3.png' %}" class="img-responsive ivo-app-logo general">
								<h2>Descarga nuestra App Movil</h2>
								<a href="#" class="ivo-app-goplay general">
									<img src="{% static 'img/google-play.png' %}">
								</a>
								<a href="#" class="ivo-app-appsto general">
									<img src="{% static 'img/appstore.png' %}">
								</a>
								<br class="clear">
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- Footer -->
		{% endblock %}


		

templates/blog/resultados.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}


{% block cssblock %}

		<style type="text/css">
			.ivo-pregunta { height: auto;}
			.ivo-form  select {width: 100%}
			body {
				background-color: white;
			}
		</style>
{% endblock %}

 {% block content%}
<!-- Castings -->
			<div class="row">
				<div class="col-md-10 col-lg-10 col-md-offset-1 ivo-blog-resultado">
					<h1>Resultados de busqueda</h1>
			    </div>
			</div>
			<!-- Blog Posts -->
			<div class="row ivo-noticias ivo-blog ivo-blog-invertido">
				<div class="col-md-10 col-lg-10 col-md-offset-1">
				    <div class="row">
					{% if posts.object_list|length == 0 %}
								<h4> No hay resultados para esta busqueda</h4>
							{% endif %}

				    {% for post in posts %}
								
				    	
				    	{% if post.categoria.nombre == 'Novedades' %}
				    	<div class="image-block col-sm-4 ivo-blog-item ivo-blog-item-extendido" style="background-image: url('{{post.imagen.url}}');">

				            <h3 style="background-color: #D8006C;">{{post.categoria}}</h3>
				    		<div>
					            <div class="ivo-blog-fecha">{{post.fecha_creacion}}</div>
					    		<h4 class="ivo-bold">{{post.titulo}}</h4>
				    		</div>
				            <a href={% url 'blog:detalle' idpost=post.id %} class="ivo-boton ivo-noticiaslink ivo-blog-novedades">Leer Mas</a>
				        </div>
				        {% elif post.categoria.nombre == 'Fanatico' %}
				        <div class="image-block col-sm-4 ivo-blog-item ivo-blog-item-extendido" style="background-image: url('{{post.imagen.url}}');">

					        <h3 style="background-color: #00C4B4;">{{post.categoria}}</h3>
					    		<div>
						            <div class="ivo-blog-fecha">{{post.fecha_creacion}}</div>
						    		<h4 class="ivo-bold">{{post.titulo}}</h4>
					    		</div>
					            <a href={% url 'blog:detalle' idpost=post.id %} class="ivo-boton ivo-noticiaslink ivo-blog-fanatico">Leer Mas</a>
					        </div>

				        {% elif post.categoria.nombre == 'Industria' %}
				        <div class="image-block col-sm-4 ivo-blog-item ivo-blog-item-extendido" style="background-image: url('{{post.imagen.url}}');">

				        	<h3 style="background-color: #0032A0;">{{post.categoria}}</h3>
					    		<div>
						            <div class="ivo-blog-fecha">{{post.fecha_creacion}}</div>
						    		<h4 class="ivo-bold">{{post.titulo}}</h4>
					    		</div>
					            <a href={% url 'blog:detalle' idpost=post.id %} class="ivo-boton ivo-noticiaslink ivo-blog-industria">Leer Mas</a>
					        </div>

				        {% elif post.categoria.nombre == 'Casting' %}
				        <div class="image-block col-sm-4 ivo-blog-item ivo-blog-item-extendido" style="background-image: url('{{post.imagen.url}}');">

				        	<h3 style="background-color: #61A60E;">{{post.categoria}}</h3>
					    		<div>
						            <div class="ivo-blog-fecha">{{post.fecha_creacion}}</div>
						    		<h4 class="ivo-bold">{{post.titulo}}</h4>
					    		</div>
					            <a href={% url 'blog:detalle' idpost=post.id %} class="ivo-boton ivo-noticiaslink ivo-blog-casting">Leer Mas</a>
					        </div>

				        {% elif post.categoria.nombre == 'Talento' %}
				        <div class="image-block col-sm-4 ivo-blog-item ivo-blog-item-extendido" style="background-image: url('{{post.imagen.url}}');">

				        	<h3 style="background-color: #FC4513;">{{post.categoria}}</h3>
					    		<div>
						            <div class="ivo-blog-fecha">{{post.fecha_creacion}}</div>
						    		<h4 class="ivo-bold">{{post.titulo}}</h4>
					    		</div>
					            <a href={% url 'blog:detalle' idpost=post.id %} class="ivo-boton ivo-noticiaslink ivo-blog-talento">Leer Mas</a>
					        </div>
					    {% endif %}    
				    	
				     {% endfor %}
				    </div>
			    </div>
			   <div class="col-md-6 col-lg-6 col-md-offset-3 ivo-blog-paginas">
				    {% if posts.has_other_pages %}
				    	<ul>
				    		{% if posts.has_previous %}
					    			<li class="ivo-blog-paginas-move">
					    			<a href="?page={{ posts.previous_page_number }}">&laquo;</a></li>
							    
				    			{% endif %}

							    {% for i in posts.paginator.page_range %}
							      {% if posts.number == i %}
						    		<li class="ivo-blog-paginas-activo">
						    			<span>{{ i }} <span class="sr-only">(current)</span></span>
						    		</li>
				    			 {% else %}
				    		<li>
				    			<a href="?page={{ i }}">{{ i }}</a>
				    		</li>
				    		{% endif %}
							    {% endfor %}
							    {% if posts.has_next %}
							      <li><a href="?page={{ posts.next_page_number }}">&raquo;</a></li>
							    
							    {% endif %}
							  </ul>
							{% endif %}
				    </div>
				</div>
			</div>
		</div>
		{% endblock %}