API/urls.py
from django.conf.urls import url
from rest_framework_jwt.views import obtain_jwt_token, verify_jwt_token, refresh_jwt_token
from .views import *

urlpatterns = [
	url(r'^menu/(?P<email>[\w.%+-_]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/$', MenuUsuarioView.as_view()),
	url(r'^numseg/(?P<email>[\w.%+-_]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/$', NumeroSeguidoresView.as_view()),
	url(r'^artistas/$',TalentosView.as_view()),
	url(r'^artistas/(?P<idcategoria>[A-Za-z]+)/$', TalentosTipoView.as_view()),
	url(r'^proveedores/$',ProveedoresView.as_view()),
	url(r'^proveedores/(?P<idcategoria>[A-Za-z]+)/$',ProveedoresTipoView.as_view()),
	url(r'^castings/$',CastingsView.as_view()),
	url(r'^castings/(?P<idcategoria>[A-Za-z0-9]+)/$',CastingsTipoView.as_view()),
	url(r'^tipoarte/$', TipoArteView.as_view()),
	url(r'^tipoindustria/$', TipoIndustriaView.as_view()),
	url(r'^registro/', RegistroView.as_view()),
	url(r'^categoria/(?P<idcategoria>[A-Za-z]+)/$', UserCategoriaView.as_view()),
	url(r'^usuario/(?P<email>[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/(?P<tab>[A-Za-z]+)/$', UsuarioView.as_view()),
	url(r'^login/', obtain_jwt_token),
    url(r'^verificar/', verify_jwt_token),
    url(r'^renovar/', refresh_jwt_token),
   ]   

casting/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .views import *

urlpatterns = [
    url(r'^inicio/$', todos, name='casting_inicio'),
    url(r'^categoria/(?P<idcategoria>[A-Za-z-\w]+)/$', casting_por_categoria, name='casting_categoria'),
    url(r'^id/(?P<idcasting>[0-9]+)/$', detalle, name='casting_detalle'),
    url(r'^crear/$', login_required(crear), name='casting_crear'),
    url(r'^guardar/$', guardar, name='casting_guardar'),
    url(r'^editar/(?P<idcasting>[0-9]+)/$', editar_casting, name='casting_editar'),
    url(r'^audicion/(?P<casting>[0-9]+)/$', audicion1, name='casting_audicion1'),
    url(r'^panel/$', login_required(panel), name='panel'),
    url(r'^audicionpanel/$', login_required(audicionpanel), name='audicionpanel'),
    url(r'^industria/(?P<idcasting>[0-9]+)/$', casting_ind, name='casting_ind'),
    url(r'^audi/(?P<idaudicion>[0-9]+)/$', casting_aud, name='casting_aud'),
    url(r'^ganador/$', casting_ganador, name='casting_ganador'),
    url(r'^config/(?P<idcasting>[0-9]+)/$', login_required(config_casting), name='casting_config'),
    url(r'^borrar/(?P<idcasting>[0-9]+)/$', login_required(borrar_casting), name='casting_borrar'),
    url(r'^borrar/audicion/(?P<idaudicion>[0-9]+)/$', login_required(borrar_audicion), name='casting_borrar_audicion'),

]

ivotalents/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from frontend import views
from django.conf.urls.static import static
from django.conf import settings
from rest_framework.urlpatterns import format_suffix_patterns
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views
import notifications.urls




urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home, name='home'),
    url(r'^facebook-login/$', views.facebook_login, name='facebook'),
    url(r'^facebook-registro/$', views.facebook_registro, name='facebook-registro'),
    url(r'^registrate/$', views.registrate, name='registro'),
    url(r'^registrate/artista/$', views.registrate_artistas, name='registro_artistas'),
    url(r'^registrate/talentos/$', views.getArtes, name='registrate'),
    url(r'^registrate/generos-artisticos/$', views.getGeneroArtisticos, name='generos_artisticos'),
    url(r'^industria/$', views.industria, name='industria'),
    url(r'^ciudad/$', views.buscar_ciudad, name='ciudad'),
    url(r'^registro/industria/$', views.RegistroIndustria, name='industria'),
    url(r'^registro/proveedor/$', views.RegistroProveedor, name='proveedor'),
    url(r'^fan/$', views.fan, name='fan'),
    url(r'^registro/fan/$', views.registrofan, name='registrofan'),
    url(r'^registro/fan/interes$', views.faninteres, name='faninteres'),
    url(r'^castings/$', views.castings, name='castings'),
    url(r'^artistadashboard/$', login_required(views.artistadashboard), name='artistadashboard'),
    url(r'^busqueda-avanzada/$', login_required(views.busqueda_avanzada), name='busqueda_avanzada'),
    url(r'^industriadashboard/$', views.industriadashboard, name='industriadashboard'),
    url(r'^crearcasting/$', views.crearcasting, name='crearcasting'),
    url(r'^seleccion-registro/$', views.registrosecundario, name='seleccionregistro'),
    url(r'^seguir/$', views.seguir, name='seguir'),
    url(r'^terminos/$', views.terminos, name='terminos'),
    url(r'^planes/$', views.planes, name='planes'),
    url(r'^pagar/$', views.pagar, name='pagar'),
    url(r'^faq/$', views.faq, name='faq'),
    url(r'^faq-busqueda/$', views.busqueda_pregunta, name='busqueda_pregunta'),
    url(r'^faq-pregunta/$', views.faqpregunta, name='faqpregunta'),
    url(r'^corporativa/$', views.corporativa, name='corporativa'),
    url(r'^corporativa/contacto/$', views.contacto, name='contacto'),
    url(r'^olvido-clave/$', views.olvidoclave, name='olvidoclave'),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),

    url(r'^mensaje/get_user/', views.get_user, name='get_user'),
    url(r'^busqueda/$', views.busqueda, name='busqueda'),
    
    #url(r'^artistas/$', views.artistas, name='listado'),

    #url(r'^accounts/',include('allauth.urls')),
    url(r'^login/', views.index, name='index'),
    url(r'^logout/', views.cerrar_sesion, name='logout'),
    url(r'^perfil/', include('perfiles.urls', namespace='perfiles')),
    url(r'^all/', include('listado.urls', namespace='listado')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^casting/', include('casting.urls', namespace='casting')),
    url(r'^api/v1/', include('API.urls', namespace='api')),
    url('^inbox/notifications/', include(notifications.urls, namespace='notifications'))
    

    
]

urlpatterns = format_suffix_patterns(urlpatterns)

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

casting/forms.py
from django import forms
from .models import Casting, Categoria, Audicion

class FormRegistro(forms.ModelForm):
    
    class Meta:
        model = Casting
        exclude = ['imagen_principal','descripcion_breve', 'autor','tatuaje','publico']


class FormAudicion(forms.ModelForm):
	
	class Meta:
		model = Audicion
		exclude = ['id_usuario', 'id_casting']
    		
       

casting/views.py
from django.shortcuts import render_to_response, render, redirect
from django.core.urlresolvers import reverse
from .models import Casting, Filtro, Audicion
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import  FormRegistro, FormAudicion
from frontend.models import User, SectorIndustria, Industria, UsuarioArteGenero
import json
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from frontend.funciones import form_invalid
from django.utils.translation import ugettext_lazy as _
from datetime import date
from django.db.models import Q
from django.core.mail import send_mail, BadHeaderError
from notifications.signals import notify


# Create your views here.
#LISTA GENERAL
def todos(request):
	if request.user.tipo_usuario == 'A':
		categorias= TipoArte.objects.all()

		filtro_1 = Q(publico=True)
		filtro_2 = Q(pais=request.user.pais.id) & Q(color_cabello=None) & Q(color_ojos=None) & Q(tatuaje='') & Q(etnia=None) & Q(publico=False)
		filtro_3 = Q(pais=None) & Q(color_cabello=request.user.color_cabello.id) & Q(color_ojos=None) & Q(tatuaje='') & Q(etnia=None) & Q(publico=False)
		filtro_4 = Q(pais=request.user.pais.id) & Q(color_cabello=request.user.color_cabello.id) & Q(color_ojos=None) & Q(tatuaje='') & Q(etnia=None) & Q(publico=False)
		filtro_5 = Q(pais=None) & Q(color_cabello=None) & Q(color_ojos=request.user.color_ojos.id) & Q(tatuaje='') & Q(etnia=None) & Q(publico=False)
		filtro_6 = Q(pais=request.user.pais.id) & Q(color_cabello=None) & Q(color_ojos=request.user.color_ojos.id) & Q(tatuaje='') & Q(etnia=None) & Q(publico=False)
		filtro_7 = Q(pais=None) & Q(color_cabello=request.user.color_cabello.id) & Q(color_ojos=request.user.color_ojos.id) & Q(tatuaje='') & Q(etnia=None) & Q(publico=False)
		filtro_8 = Q(pais=request.user.pais.id) & Q(color_cabello=request.user.color_cabello.id) & Q(color_ojos=request.user.color_ojos.id) & Q(tatuaje='') & Q(etnia=None) & Q(publico=False)
		filtro_9 = Q(pais=None) & Q(color_cabello=None) & Q(color_ojos=None) & Q(tatuaje=request.user.tatuaje) & Q(etnia=None) & Q(publico=False)
		filtro_10 = Q(pais=request.user.pais.id) & Q(color_cabello=None) & Q(color_ojos=None) & Q(tatuaje=request.user.tatuaje) & Q(etnia=None) & Q(publico=False)
		filtro_11 = Q(pais=None) & Q(color_cabello=request.user.color_cabello.id) & Q(color_ojos=None) & Q(tatuaje=request.user.tatuaje) & Q(etnia=None) & Q(publico=False)
		filtro_12 = Q(pais=request.user.pais.id) & Q(color_cabello=request.user.color_cabello.id) & Q(color_ojos=None) & Q(tatuaje=request.user.tatuaje) & Q(etnia=None) & Q(publico=False)
		filtro_13 = Q(pais=None) & Q(color_cabello=None) & Q(color_ojos=request.user.color_ojos.id) & Q(tatuaje=request.user.tatuaje) & Q(etnia=None) & Q(publico=False)
		filtro_14 = Q(pais=request.user.pais.id) & Q(color_cabello=None) & Q(color_ojos=request.user.color_ojos.id) & Q(tatuaje=request.user.tatuaje) & Q(etnia=None) & Q(publico=False)
		filtro_15 = Q(pais=None) & Q(color_cabello=request.user.color_cabello.id) & Q(color_ojos=request.user.color_ojos.id) & Q(tatuaje=request.user.tatuaje) & Q(etnia=None) & Q(publico=False)
		filtro_16 = Q(pais=request.user.pais.id) & Q(color_cabello=request.user.color_cabello.id) & Q(color_ojos=request.user.color_ojos.id) & Q(tatuaje=request.user.tatuaje) & Q(etnia=None) & Q(publico=False)
		filtro_17 = Q(pais=None) & Q(color_cabello=None) & Q(color_ojos=None) & Q(tatuaje='') & Q(etnia=request.user.etnia.id) & Q(publico=False)
		filtro_18 = Q(pais=request.user.pais.id) & Q(color_cabello=None) & Q(color_ojos=None) & Q(tatuaje='') & Q(etnia=request.user.etnia.id) & Q(publico=False)
		filtro_19 = Q(pais=None) & Q(color_cabello=request.user.color_cabello.id) & Q(color_ojos=None) & Q(tatuaje='') & Q(etnia=request.user.etnia.id) & Q(publico=False)
		filtro_20 = Q(pais=request.user.pais.id) & Q(color_cabello=request.user.color_cabello.id) & Q(color_ojos=None) & Q(tatuaje='') & Q(etnia=request.user.etnia.id) & Q(publico=False)
		filtro_21 = Q(pais=None) & Q(color_cabello=None) & Q(color_ojos=request.user.color_ojos.id) & Q(tatuaje='') & Q(etnia=request.user.etnia.id) & Q(publico=False)
		filtro_22 = Q(pais=request.user.pais.id) & Q(color_cabello=None) & Q(color_ojos=request.user.color_ojos.id) & Q(tatuaje='') & Q(etnia=request.user.etnia.id) & Q(publico=False)
		filtro_23 = Q(pais=None) & Q(color_cabello=request.user.color_cabello.id) & Q(color_ojos=request.user.color_ojos.id) & Q(tatuaje='') & Q(etnia=request.user.etnia.id) & Q(publico=False)
		filtro_24 = Q(pais=request.user.pais.id) & Q(color_cabello=request.user.color_cabello.id) & Q(color_ojos=request.user.color_ojos.id) & Q(tatuaje='') & Q(etnia=request.user.etnia.id) & Q(publico=False)
		filtro_25 = Q(pais=None) & Q(color_cabello=None) & Q(color_ojos=None) & Q(tatuaje=request.user.tatuaje) & Q(etnia=request.user.etnia.id) & Q(publico=False)
		filtro_26 = Q(pais=request.user.pais.id) & Q(color_cabello=None) & Q(color_ojos=None) & Q(tatuaje=request.user.tatuaje) & Q(etnia=request.user.etnia.id) & Q(publico=False)
		filtro_27 = Q(pais=None) & Q(color_cabello=request.user.color_cabello.id) & Q(color_ojos=None) & Q(tatuaje=request.user.tatuaje) & Q(etnia=request.user.etnia.id) & Q(publico=False)
		filtro_28 = Q(pais=request.user.pais.id) & Q(color_cabello=request.user.color_cabello.id) & Q(color_ojos=None) & Q(tatuaje=request.user.tatuaje) & Q(etnia=request.user.etnia.id) & Q(publico=False)
		filtro_29 = Q(pais=None) & Q(color_cabello=None) & Q(color_ojos=request.user.color_ojos.id) & Q(tatuaje=request.user.tatuaje) & Q(etnia=request.user.etnia.id) & Q(publico=False)
		filtro_30 = Q(pais=request.user.pais.id) & Q(color_cabello=None) & Q(color_ojos=request.user.color_ojos.id) & Q(tatuaje=request.user.tatuaje) & Q(etnia=request.user.etnia.id) & Q(publico=False)
		filtro_31 = Q(pais=None) & Q(color_cabello=request.user.color_cabello.id) & Q(color_ojos=request.user.color_ojos.id) & Q(tatuaje=request.user.tatuaje) & Q(etnia=request.user.etnia.id)	 & Q(publico=False)
		filtro_32 = Q(pais=request.user.pais.id) & Q(color_cabello=request.user.color_cabello.id) & Q(color_ojos=request.user.color_ojos.id) & Q(tatuaje=request.user.tatuaje) & Q(etnia=request.user.etnia.id)  & Q(publico=False)
		filtro =  filtro_2 | filtro_3 | filtro_4 | filtro_5 | filtro_6 | filtro_7 | filtro_8 | filtro_9 | filtro_10 | filtro_11 | filtro_12 | filtro_13 | filtro_4 | filtro_15 | filtro_16 | filtro_17 | filtro_18 | filtro_19 | filtro_20 | filtro_21 | filtro_22 | filtro_23 | filtro_24 | filtro_25 | filtro_26 | filtro_27 | filtro_28 | filtro_29 | filtro_30 | filtro_31 | filtro_32

		#buscar talentos en Tabla_Filtro
		filtro_genero = Q()
		for portalento in Filtro.objects.filter(id_talento=GeneroArtistico.objects.get(id=UsuarioArteGenero.objects.get(id_usuario=request.user).id_genero.id).id_tipo_arte.id):
			for porgenero in portalento.id_generos.all():
				if UsuarioArteGenero.objects.get(id_usuario=request.user).id_genero == porgenero:
					filtro_genero.add(Q(id=portalento.id_casting.id),Q.OR)

		
		all_casting = Casting.objects.filter((filtro & filtro_genero)|filtro_1).order_by("fecha_fin")
		all_casting = all_casting.filter(fecha_fin__gte=date.today())
		
		#import pdb; pdb.set_trace()
		paginator = Paginator(all_casting, 10) 
		page = request.GET.get('page',1)
		try:
			castings = paginator.page(page)
		except PageNotAnInteger:
	        # If page is not an integer, deliver first page.
			castings = paginator.page(1)
		except EmptyPage:
	        # If page is out of range (e.g. 9999), deliver last page of results.
			castings = paginator.page(paginator.num_pages)
			#import pdb;   pdb.set_trace()
		#import pdb;   pdb.set_trace()
		return render(request, "casting/inicio.html", {"castings": castings, "categorias":categorias })
	elif request.user.tipo_usuario == 'I' or request.user.tipo_usuario == 'P':
		all_casting = Casting.objects.filter(fecha_fin__gte=date.today())
		categorias = TipoArte.objects.all()

		paginator = Paginator(all_casting, 10) 
		page = request.GET.get('page',1)
		try:
			castings = paginator.page(page)
		except PageNotAnInteger:
	        # If page is not an integer, deliver first page.
			castings = paginator.page(1)
		except EmptyPage:
	        # If page is out of range (e.g. 9999), deliver last page of results.
			castings = paginator.page(paginator.num_pages)
		return render(request, "casting/inicio.html", {"castings": castings, "categorias":categorias })
	else:
		return HttpResponseRedirect( "/",{})


#LISTADO POR CATEGORIA
def casting_por_categoria(request, idcategoria):
	categorias= TipoArte.objects.all()
	#import pdb; pdb.set_trace()
	categoria = Filtro.objects.filter(id_talento=idcategoria).values_list('id_casting',flat=True)

	all_casting = Casting.objects.filter(id__in=categoria,fecha_fin__gte=date.today())
	paginator = Paginator(all_casting, 10) # Show 25 contacts per page	
	page = request.GET.get('page',1)
	try:
		castings = paginator.page(page)
	except PageNotAnInteger:
        # If page is not an integer, deliver first page.
		castings = paginator.page(1)
	except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
		castings = paginator.page(paginator.num_pages)
	#import pdb;   pdb.set_trace()
	return render(request, "casting/inicio.html", {"castings": castings,"categorias":categorias })

#DETALLES DE UN CASTING
def detalle(request,idcasting):

	casting = Casting.objects.get(id=idcasting)
	asociados= Casting.objects.filter(autor=casting.autor).exclude(id=idcasting)[:2]
	#import pdb;   pdb.set_trace()
	return render(request,"casting/detalle.html", {"casting": casting, "asociados": asociados },)


#def crear(request):
#	return render_to_response("casting/crear.html",{},)

#CREACION DE UN CASTING
def crear(request):	

	if request.user.tipo_usuario == 'I':
		categorias=Industria.objects.filter(tipo='I')
		colores_ojos = Ojos.objects.all()
		colores_cabellos = Cabellos.objects.all()
		etnias= Etnia.objects.all()

templates/footer.html
{% load staticfiles %}
<div class="container-fluid ivo-footer ivo-footer-topBck">
    <div class="container">
        <div class="row ivo-footer-top">
            <div class="col-xs-8 col-xs-offset-2 col-sm-3 col-sm-offset-0 col-md-3 col-lg-3 ivo-footer-logo">
                <img src="{% static 'img/ivo-lg1.png' %}" class="img-responsive">
            </div>
            <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3 ivo-footer-lista1">
                <ul>
                    <li>
                        <a href="/corporativa/">acerca de</a>
                    </li>
                    <li>
                        <a href="#">contacto</a>
                    </li>
                    <li>
                        <a href="/password_reset/">olvido contrase&ntilde;a?</a>
                    </li>
                    
                    <li>
                        <a href="/terminos/">terminos y condiciones</a>
                    </li>
                    <li>
                        <a href="/faq/">preguntas frecuentes</a>
                    </li>
                </ul>
            </div>


            <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3 ivo-footer-lista2">
                        <ul>
                            <li>

                                <a data-toggle="collapse" data-target="#artista_collapse" style="cursor:pointer">artistas</a>
                            </li>
                            <div id="artista_collapse" class="collapse">
                                       {% if user.is_authenticated %}
                                {% if user.tipo_usuario != 'F' %}

                                <li>
                                    <a href="/planes/"  class="ivo-footer-top-blanco">paquetes</a>
                                </li>
                                {%endif%}
                            {%endif%}
                            <li>
                                <a href="#preguntas_artistas" class="ivo-footer-top-blanco">preguntas frecuentes</a>
                            </li>
                            <li>
                                <a href="{% url 'registrate' %}" class="ivo-footer-top-blanco">registrate</a>
                            </li>
                            </div>
                            <li>
                                <a data-toggle="collapse" data-target="#industria_collapse" style="cursor:pointer">industria</a>
                            </li>
                                <div id="industria_collapse" class="collapse">
                                       {% if user.is_authenticated %}
                                {% if user.tipo_usuario != 'F' %}

                                <li>
                                    <a href="/planes/"  class="ivo-footer-top-blanco">paquetes</a>
                                </li>
                                {%endif%}
                            {%endif%}
                            <li>
                                <a href="#preguntas_industria" class="ivo-footer-top-blanco">preguntas frecuentes</a>
                            </li>
                            <li>
                                <a href="{% url 'industria' %}" class="ivo-footer-top-blanco">registrate</a>
                            </li>
                            </div>

                            <li>
                                <a data-toggle="collapse" data-target="#fan_collapse" style="cursor:pointer" >fans</a>
                            </li>
                                <div id="fan_collapse" class="collapse">
                                       
                            <li>
                                <a href="#preguntas_fan" class="ivo-footer-top-blanco">preguntas frecuentes</a>
                            </li>
                            <li>
                                <a href="{%url 'fan' %}" class="ivo-footer-top-blanco">registrate</a>
                            </li>
                            </div>
                            <li>
                                <a >casting</a>
                            </li>
                        </ul>
                    </div>
            
            <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3 ivo-footer-listaS">
                <ul class="ivo-footer-social">
                    <li><span class="social_facebook_circle"></span></li>
                    <li><span class="social_twitter_circle"></span></li>
                    <li><span class="social_instagram_circle"></span></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid ivo-footer ivo-footer-bottomBck">
    <div class="container ivo-footer-bottomBck">
        <div class="row ivo-footer-bottom">
            <div class="col-md-8 col-lg-8 col-md-offset-2">
                <p>IVO talents, todos los derechos reservados, 2016</p>
            </div>
        </div>
    </div>
</div>
<!-- Menu Lateral -->
<div class="ivo-menu-principal-panel">
    <ul>
        <li class="ivo-menu-principal-panel-encabezado">
            <span class="icon_close" aria-hidden="true" id="ivo-boton-menu-cerrar"></span>
            <p>Menu</p>
        </li>
        <li class="ivo-menu-principal-panel-social">
            <span class="social_facebook_circle"></span>
            <span class="social_twitter_circle"></span>
            <span class="social_instagram_circle"></span>
        </li>
        <li class="ivo-menu-principal-panel-menu">
            <ul>
                {% if user.is_authenticated %}
                <li>
                    <a id="enlace-talentos" href={% url 'listado:artistas' %} class="naranja">Talentos</a>
                </li>
                {% if user.tipo_usuario != 'F' %}
                <li>
                    <a id="enlace-industria" href={% url 'listado:industrias' %} class="azul">Industria</a>
                </li>
                <li>
                    <a id="enlace-casting" href={% url 'casting:casting_inicio' %} class="verde">Casting / Audiciones</a>
                </li>
                {%endif%}
                <li>
                    <a id="enlace-proveedores" href={% url 'listado:proveedores' %} class="rosa">Proveedores</a>
                </li>
                {% endif %}
                <li>
                    <a id="enlace-blog" href={% url 'blog:todos' %} class="negro">Blog</a>
                </li>
                 {% if user.is_authenticated %}
                <li id='li_encuentra'>
                    <a id='encuentra' href="#" class="azulClaro"><span class="glyphicon glyphicon-search" aria-hidden="true"> </span> Encuentra</a>
                </li>
     <li id='form_encuentra' >
                    <form id='input_encuentra' action="{% url 'busqueda' %}" method="GET" >                           
                        <input type="text" name="q">

                        <button type="submit">
                            <span class="glyphicon glyphicon-search"></span>
                        </button>
                        
                    </form>
                    
                </li>
                 {% endif %}
                <li class="ivo-menu-principal-panel-buttonAp">
                    <button class="ivo-boton-fondoInpt" style="margin-top: 8px">
                        <span class="ivo-borde-transparente ivo-menu-buttonAP">
                            <img src="{% static 'img/ivo-lg2.png' %}"> IVO | App
                        </span>
                    </button>
                </li>
            </ul>
        </li>

    </ul>
</div>

templates/olvido-clave.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}


{% block cssblock %}
	<link href="{% static 'css/jquery.countdown.css' %}" rel="stylesheet">
		<style type="text/css">
			.ivo-pregunta {
				background-image: url("{%static 'img/login.jpg' %}");
				min-height: 100%;
    			height: 100%;
    			margin-top: 
			}
			.ivo-formartista-gray {height: 100%;}
		</style>
{% endblock %}

{%block content%}

<div class="container-fluid ivo-pregunta ivo-recuperarClave">
			<div class="ivo-layer-gry ivo-formartista-gray"></div>
			<div class="container ivo-recuperarClave">
				<div class="row ivo-login-header">
					<div class="col-sm-8 col-md-6 col-lg-6 col-sm-offset-2 col-md-offset-3 ivo-login-header-olvido">
						<h1 class="olv-clave">&iquest;Olvid&oacute; </br> contrase&ntilde;a?</h1>
					</div>
				</div>
				<div class="row">
					<div class="col-sm-8 col-md-6 col-lg-6 col-sm-offset-2 col-md-offset-3">
						<div class="ivo-login-header-texto">
							Por favor enviar un correo para recuperar contrase&ntilde;a
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-sm-8 col-md-6 col-lg-6 col-sm-offset-2 col-md-offset-3">
						<form method="POST" class="ivo-form">
							<div class="row">
								<div class="col-md-12 col-lg-12">
									<input type="text" name="nombre" placeholder="Usuario">
								</div>
								<div class="col-md-12 col-lg-12">
									<input type="text" name="nombre" placeholder="Correo">
								</div>
							</div>
							<div class="row">
								<div class="col-md-6 col-lg-6 col-md-offset-3" style="text-align: center;">
									<button class="ivo-boton-fondoInpt ivo-borde-trs-verde" style="margin-top: 8px">
										<span class="ivo-back-trs-verde ivo-borde-transparente">
											Enviar
										</span>
									</button>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>

{%endblock%}